tag: zh-reg-classification_zeroshot
task: reg-relation-classification_zeroshot
dataset_path:
dataset_name: default
test_split: test
output_type: multiple_choice
doc_to_text: '{{query}}'
doc_to_target: gold
doc_to_choice: choices
#fewshot_config:
#  sampler: first_n
fewshot_split: train
num_fewshot: 0
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
